### PR TITLE
Impr/better manifest

### PR DESCRIPTION
**Pull request by linuxbandit**

### CODE REVIEW

**Comment by linuxbandit** [comment]
This is the PR where everything gets together - notice that before merging this, the other PRs must be merged (I'll take care of it)

**Comment by linuxbandit** [comment]
I have merged your repos, I want one last check in Core. 

After this I will bump the submodules in this branch, and merge to master (need your review tho)

**Review by serge1peshcoff — APPROVED** [review]

**Comment by linuxbandit** [comment]
i can merge this afternoon

**Comment by linuxbandit** [comment]
i will merge then add the things i told you about (the extra services, and separate the extra services between scrapers and displays)

**Comment by serge1peshcoff** [comment]
Please don't exclude discounts and instead add it with the new fixes, I've fixed this issue you were referring to in your PR

**Pull request merged**
