### PR TITLE
fix: orchestrate_docker was not changing fe perm

### PR DESCRIPTION
**Pull request by linuxbandit**
further add variables on vagrantfile

### CODE REVIEW

**Review by WikiRik — APPROVED** [review]

**Comment by WikiRik** [comment]
We'll need a similar fix for non-Vagrant users, right?

**Comment by linuxbandit** [comment]
similar in which way? pin of docker?

Generally I don't want to support other unofficial methods when one is advised. As long term solution what should happen truly is an ansible playbook that provisions whatever one wants: be it the local machine, the local VM, or the remote server

**Comment by WikiRik** [comment]
The frontend permissions, or this only for the very initial build of frontend?

**Comment by linuxbandit** [comment]
the frontend fix is for the first run in development mode, via vagrant; in the readme I could add in the 'troubleshoot' section a note about the 403, then i will push and merge

**Review by WikiRik — APPROVED** [review]

**Pull request merged**
