### PR TITLE
Added docker command to helper script

### PR DESCRIPTION
**Pull request by blacksph3re**
This way currently unsupported docker commands can be accessed again through the helper script

### CODE REVIEW

**Comment by linuxbandit** [comment]
Can you provide usage examples?

**Comment by serge1peshcoff** [comment]
Actually it can be quite handy when we want to run some custom command. For example if I want to rebuild just one specific module, I can't do `./helper.sh --build oms-statutory`, it'll rebuild the whole system. Flso there is no `docker-compose ps` like command.
We can add such commands later, but generally it'd be nice to have the ability to run something custom (though we should not abuse it and stick to the non-custom ones).

**Comment by blacksph3re** [comment]
Exactly, other commands which are currently unsupported are scale, port, run and some other which I don't think we need atm. It's not for everyday's usage, but in a case of emergency when we need some custom command, it would be quite handy to use it

**Comment by serge1peshcoff** [comment]
Actually one of the usecases I needed. I needed to drop postgresql container for statutory as I've messed it up and there was no way to do it other than copying that big command and adding what I needed to add (`rm -v postgres-oms-statutory`).

(on the local system ofc, not on prod :D)

**Review by serge1peshcoff — APPROVED** [review]

**Comment by serge1peshcoff** [comment]
Rebased here: https://github.com/AEGEE/oms-docker/pull/95, so superseded.

**Pull request closed without merging**
