### PR TITLE
Update vagrant environment

### PR DESCRIPTION
**Pull request by linuxbandit**
This is (yet) another update (I will close #29), in which the VM for developers of windows and mac is updated with several features:

- add updated OS to reflect what we'll have on fraktis
- add updated bootstrap method
- add utility containers for orchestration and CI 

README was updated accordingly

### CODE REVIEW

**Comment by i3anaan** [comment]
Looks really good.
What is portainer?

**Review by i3anaan — APPROVED** [review]
Under the assumption that you have tested the vagrant installation I approve of this!

**Comment by linuxbandit** [comment]
You can test it yourself too ;) and you can get a hang of what is portainer (I just briefly showed you at agora, it's basically an orchestrator but simpler than rancher)

`git clone --recursive -b update-vagrant https://github.com/linuxbandit/oms-docker`
`cd oms-docker`
`vagrant up`

note that for that you *must* edit your `/etc/hosts` because traefik serves it through "portainer.*" e.g. http://portainer.appserver/ only (I mean, also with http://portainer.localhost:8888/ but you should edit the hosts anyway so why not using `appserver` :p )

**Comment by linuxbandit** [comment]
will merge tomorrow after andrea tries it

**Pull request merged**
