### PR TITLE
fix(ci): Remove git submodule from shell lint

### PR DESCRIPTION
**Pull request by WikiRik**
The shell linter did updates on the submodules, but we're updating the submodules regularly so it just slowing the check down imo

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
it also should be moved to submodules, e.g. each submodule should have its own shellcheck (probably I did it already)

**Review by serge1peshcoff — APPROVED** [review]

**Comment by linuxbandit** [comment]
actually there's no shell at all in the subs, so it was a good removal

**Comment by WikiRik** [comment]
In the docker folders there is bootstrap.sh right? Is that not taken into account?

**Comment by linuxbandit** [comment]
only sometimes, and it is neglectable

**Pull request merged**
