### PR TITLE
Add basic monitoring

### PR DESCRIPTION
**Pull request by blacksph3re**
I added service monitoring with grafana. The login credentials are our widely used default credentials, access with localhost:8080. Merge #37 first

### CODE REVIEW

**Comment by i3anaan** [comment]
```bash ./oms.sh exec -T -d omsserviceregistry true 2>/dev/null || exit 1```
Failed twice in a row.

**Comment by i3anaan** [comment]
Same issue as explained in #37 

Also, a seemingly additional issue:

```
cadvisor_1                        | 	-exec CMD ARG + Run CMD with {} replaced by list of file names
cadvisor_1                        | 	-delete		Delete current file/directory. Turns on -depth option
cadvisor_1                        | ; err: exit status 1, extraDiskErr: <nil>
cadvisor_1                        | E0918 15:29:18.993527       1 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: <nil>, rootInodeErr: cmd [find /var/lib/docker/aufs/diff/1bf8bb8e245df5f4d2ba5b2745e9e9e3fc86bf1c649dfb7e7f133603aab2ccc2 -xdev -printf .] failed. stderr: find: unrecognized: -printf
```

**Review by i3anaan — CHANGES_REQUESTED** [review]
Errors present in the log file

**Comment by linuxbandit** [comment]
Me and Sergey are cleaning up the branches
Please refactor adding one change at the time (this also brings alastair), we are not gonna delete the branch of course - can you wait for us to merge the new core though?

**Pull request closed without merging**
