### PR TITLE
Improved testing: Added local loopback test.

### PR DESCRIPTION
**Pull request by i3anaan**

### CODE REVIEW

**Comment by i3anaan** [comment]
FYI: This also includes the latest oms-core commit.

**Review by linuxbandit — APPROVED** [review]
Nice! Are you planning to add more ? Should be fine to find something that lets API testing

**Comment by i3anaan** [comment]
@linuxbandit The idea was that this would only test the network configuration/setup (mainly travis / omscore-nginx). For this I felt a simple ping would be enough, leaving functional API testing to the core tests. (This does however currently act differently due to the php-fpm setup https://oms-project.atlassian.net/browse/CORE-112).

As the system increases in microservices it could be cool to have some combined actions tested, for now this is not the case though.

**Comment by i3anaan** [comment]
NOTE: Default branch has been changed to `dev`.

**Pull request merged**
