### PR TITLE
Added alastair

### PR DESCRIPTION
**Pull request by blacksph3re**
Alastair is a cooking service written in elixir. It can be used to plan the food for events

### CODE REVIEW

**Comment by i3anaan** [comment]
Still need to have some time to look into this, probably will have so tomorrow.

**Comment by i3anaan** [comment]
I might be stupid, but how can I get to it? It is not in the menu for me :stuck_out_tongue:

**Comment by i3anaan** [comment]
Additionally: It is not enabled in oms.sh by default, and I think it is not being checked to be running by Travis, could you change this?

**Comment by i3anaan** [comment]
Okay disregard the not getting to it part for now: The git repo of alastair is empty for me.

I checked out to this branch and did `git submodule update`, and it succesfully added alastair to the submodule file, however the folder is empty. Additionally when in the folder git status says it is up to date.

Any ideas? How did you do it?

**Comment by i3anaan** [comment]
This seems to be the issue:

```
i3anaan@i3anaan-Legion:~/projects/oms-docker/alastair$ git remote -v
origin	https://github.com/AEGEE/oms-docker.git (fetch)
origin	https://github.com/AEGEE/oms-docker.git (push)
```

**Comment by i3anaan** [comment]
Okay I need to look into this better, might have time for that later today. Might go for a full folder reset. Maybe someone else can see if they run into the same issue? @serge1peshcoff ?

**Comment by blacksph3re** [comment]
I just tried a git clone --recursive --branch add-alastair https://github.com/AEGEE/oms-docker.git and the folder wasn't empty...

**Comment by blacksph3re** [comment]
maybe try this one? https://stackoverflow.com/questions/1030169/easy-way-to-pull-latest-of-all-git-submodules

**Comment by blacksph3re** [comment]
Ok @i3anaan I added it to tests and auto-activated it, so I think it should be mergeable now. However the frontend of alastair partially depends on https://github.com/AEGEE/oms-neo-core/pull/61, maybe we should merge that one first?

**Comment by i3anaan** [comment]
Got it working on a clean install, that is a good sign. (I'd still rather have a solution to prevent having to clean-install, I will look into that later)
Before merging, however, I would like to see the logging level changed. It is currently outputting debug level messages, which I find unnecessary. I tried changing this myself, but that didn't seem to work. Since I do not know elixir, I'd like to ask you to fix the log level.

**Review by i3anaan — CHANGES_REQUESTED** [review]
Log level should be lower.

**Comment by i3anaan** [comment]
Found the command to fix the empty-folder issue when switching to Alastair on an existing installation:
```
git submodule update --init
```
(Called in `oms-docker` folder)

So that issue is fixed, remaining is the log level.

**Review by i3anaan — APPROVED** [review]

**Pull request merged**
