### PR TITLE
Add https auto configuration with LetsEncrypt

### PR DESCRIPTION
**Pull request by linuxbandit**

### CODE REVIEW

**Comment by blacksph3re** [comment]
Ah brilliant... on the first looks it seems like it would work, I didn't remember you could explicitly specify domains

**Comment by linuxbandit** [comment]
tried with another domain and it works nice, so I put the "target domain" to be ready. Later on we can add more subdomains (but it'll be also up to Wim for adding them to dns)

I talk about subdomains because it's much easier to configure traefik for a subdomain than not for a HostPath (and maybe hostpath is going to be modified by our app? we should avoid overwriting)

**Review by blacksph3re — APPROVED** [review]
I will merge it as it seems to work

**Review by serge1peshcoff — APPROVED** [review]
I trust you on that :D

**Pull request merged**
