### PR TITLE
fix(logstash): fix services logs processing

### PR DESCRIPTION
**Pull request by serge1peshcoff**
I've renamed the containers but did not update the logstash config, time to do so.

### CODE REVIEW

**Comment by WikiRik** [comment]
Do we want to add stuff for the gsuite-wrapper as well?

**Comment by serge1peshcoff** [comment]
I'm not sure about that, we may need to update gsuite-wrapper's logging for that. I'll check that later

**Comment by linuxbandit** [comment]
why removing the stuff below? it was elixir logging way, which now is standardised?

**Comment by serge1peshcoff** [comment]
@linuxbandit because core now logs in JSON, we don't need to parse it. only service writing in elixir format now is mailer

**Review by linuxbandit — APPROVED** [review]
thanks, thought so

**Pull request merged**
