### PR TITLE
feat: differentiate between linux and mac

### PR DESCRIPTION
**Pull request by linuxbandit**
this is for a no-vagrant setup, it is bad bad bad to not use vagrant

@serge1peshcoff I assigned you because you should try it, I don't understand what's wrong with my (g)xargs. Probably not the gnu one, idk I have a lot of troubles with GNU tools even if I installed them explicitly (e.g. gsed etc)

### CODE REVIEW

**Review by serge1peshcoff — APPROVED** [review]

**Comment by linuxbandit** [comment]
@serge1peshcoff have you tried it? I mentioned having problems with gxargs

**Comment by serge1peshcoff** [comment]
I also have issues with quotes:

```
# in .env
TEST_VAR="contains qoutes"

# in .helper.sh
if [[ $(uname) == "Linux" ]]; then
# shellcheck disable=SC2046
  export $(grep -v '^#' "${DIR}/.env" | xargs -d '\n')
else #macos
# shellcheck disable=SC2046
  export $(grep -v '^#' "${DIR}/.env" | gxargs -0 -d '\n')
  echo "TEST_VAR $TEST_VAR"
fi

# output
$ ./helper.sh --list
./helper.sh: line 164: export: `qoutes"': not a valid identifier
TEST_VAR "contains
```

**Comment by WikiRik** [comment]
@serge1peshcoff is that issue not just due to you having a space in the variable?

**Comment by linuxbandit** [comment]
won't do, no vagrant = bad

**Pull request closed without merging**
