### PR TITLE
chore: add clarity on scripts, update readme

### PR DESCRIPTION
**Pull request by linuxbandit**
For nils

### CODE REVIEW

**Review by serge1peshcoff — APPROVED** [review]

**Comment by linuxbandit** [comment]
Do you think that what you suggested on slack about the clean start is understandable from this guide?

**Comment by serge1peshcoff** [comment]
I'd say yes, except I don't see the `git submodule foreach git pull origin master` here for pulling the latest services dockerfile. other question is, given that the tag is always `latest` in docker-compose, do we ever need it?

**Comment by linuxbandit** [comment]
the way it should be is that oms-docker versions are always updated with the latest module, so for every new release of a microservice, a `make bump` is called on this repo

**Comment by linuxbandit** [comment]
I will merge it later today

**Pull request merged**
