### PR TITLE
fix(traefik): fixed Jira/Confluence host

### PR DESCRIPTION
**Pull request by serge1peshcoff**
`s/oms-project.atlassian.net/myaegee.atlassian.net`

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@mibaru-aegee check this out, after merging this the Confluence pages should be displayed properly

**Review by WikiRik — APPROVED** [review]

**Review by linuxbandit — APPROVED** [review]

**Review by linuxbandit — CHANGES_REQUESTED** [review]
it is in two files, not just one

**Comment by serge1peshcoff** [comment]
@linuxbandit the other one was already correct

**Comment by serge1peshcoff** [comment]
https://github.com/AEGEE/oms-docker/blob/16aa3fa9c97c2880ebc27350b668013022cc2e78/oms-global/docker/traefik/traefik.toml.template#L160 the production one is okay already, maybe I've fixed it before

**Review by linuxbandit — APPROVED** [review]

**Pull request merged**
