### PR TITLE
fix(lint): greenify hadolint

### PR DESCRIPTION
**Pull request by serge1peshcoff**
removed fetching submodules when running hadolint, should fix it.

### CODE REVIEW

**Review by linuxbandit — COMMENTED** [review]
shit, thought I commented yesterday but nope - anyway, I was wondering if we do have dockerfiles at all here/we will have?
CircleCI shows no file matched

**Comment by serge1peshcoff** [comment]
Seems like no

**Comment by serge1peshcoff** [comment]
I'd rather leave it in case we'll have dockerfiles here

**Comment by serge1peshcoff** [comment]
@linuxbandit ping

**Review by linuxbandit — APPROVED** [review]

**Pull request merged**
