### PR TITLE
Add basic MTA on a container (MEMB-299)

### PR DESCRIPTION
**Pull request by linuxbandit**
The MTA was supposed to be native, but for a starter we all agreed to
have it in a container. This is by no means complete as it needs testing
by the app etc, but the most basic settings are there

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
I suggest doing it in oms-mailer as it is tightly coupled with it, what do you think?

**Comment by linuxbandit** [comment]
true! Nico you can take the main.cf, or merge, or whatever :)

**Comment by blacksph3re** [comment]
oh I didn't see this one. I will replace my version with this one, I added one to oms-mailer too.

**Comment by linuxbandit** [comment]
then close it when you want

**Comment by linuxbandit** [comment]
@blacksph3re I'd say we can close this, right?

**Pull request closed without merging**
