### PR TITLE
Traefik

### PR DESCRIPTION
**Pull request by linuxbandit**
This change introduces Traefik as reverse proxy to serve all our app.

**NOTE** You will need to configure `/etc/hosts` to have `appserver` as alias for either `localhost` (if using pure Docker) or `192.168.192.168` (if using through Vagrant). This is explained in the README anyway.

### CODE REVIEW

**Comment by linuxbandit** [comment]
@serge1peshcoff for some reason (wrong branching I guess), old commits are still there o_O
I advise you to delete all branches from AEGEE/oms-docker when you merge this into, and do the same on your fork and local!

**Comment by linuxbandit** [comment]
No, nevermind, only take care of your forked + local, I will take care of this one

**Comment by serge1peshcoff** [comment]
I can't run a bootstrapping process on my PC:

```
sergeypeshkov@pcAtWork ~/tmp/oms-docker/docker docker-compose logs -f omscore-bootstrap && docker-compose logs -f omsevents-bootstrap
Attaching to docker_omscore-bootstrap_1
: not foundtstrap_1         | /root/bootstrap.sh: 2: /root/bootstrap.sh: 
omscore-bootstrap_1         | /root/bootstrap.sh: 34: /root/bootstrap.sh: Syntax error: "fi" unexpected (expecting "then")
docker_omscore-bootstrap_1 exited with code 2
Attaching to docker_omsevents-bootstrap_1
: not foundootstrap_1       | /usr/scripts/bootstrap.sh: 2: /usr/scripts/bootstrap.sh: 
omsevents-bootstrap_1       | /usr/scripts/bootstrap.sh: 37: /usr/scripts/bootstrap.sh: Syntax error: end of file unexpected (expecting "do")
docker_omsevents-bootstrap_1 exited with code 2
```

**Comment by linuxbandit** [comment]
That's weird, I didn't touch oms-core bootstrapper. I will have a look

**Comment by linuxbandit** [comment]
actually I didn't touch the bootstrapper scripts at all?!

**Comment by linuxbandit** [comment]
I close this because I submitted a better one. Maybe also there will be less previous commits?

**Pull request closed without merging**
