### PR TITLE
Make it just start

### PR DESCRIPTION
**Pull request by linuxbandit**
Decoupled docker-compose and docker-stack (former is v2 and latter v3)
Dockerfile was corrected
Makefile was removed a command just for safety in case of non-vagrant
use

### CODE REVIEW

**Comment by blacksph3re** [comment]
You use absolute paths in the dockerfile. Please do not do so, I don't have these paths and a production environment might also not. Either just use named volumes without a path or use relative ones.

**Comment by linuxbandit** [comment]
where?

**Comment by linuxbandit** [comment]
you mean docker-compose, not dockerfile?

**Comment by blacksph3re** [comment]
oh yeah, true, in the docker-compose.yml. I couldn't leave inline comments for some reason

**Pull request merged**
